
from pydantic import BaseModel
from typing import Union

# Write base classes for the data model dict_data
class InputData(BaseModel):
    x0: Union[float, str]
    x1: Union[float, str]
    x2: Union[float, str]
    x3: Union[float, str]
    x4: Union[float, str]
    x5: str
    x6: Union[float, str]
    x7: Union[float, str]
    x8: Union[float, str]
    x9: Union[float, str]
    x10: Union[float, str]
    x11: Union[float, str]
    x12: Union[float, str]
    x13: Union[float, str]
    x14: Union[float, str]
    x15: Union[float, str]
    x16: Union[float, str]
    x17: Union[float, str]
    x18: Union[float, str]
    x19: Union[float, str]
    x20: Union[float, str]
    x21: Union[float, str]
    x22: Union[float, str]
    x23: Union[float, str]
    x24: Union[float, str]
    x25: Union[float, str]
    x26: Union[float, str]
    x27: Union[float, str]
    x28: Union[float, str]
    x29: Union[float, str]
    x30: Union[float, str]
    x31: str
    x32: Union[float, str]
    x33: Union[float, str]
    x34: Union[float, str]
    x35: Union[float, str]
    x36: Union[float, str]
    x37: Union[float, str]
    x38: Union[float, str]
    x39: Union[float, str]
    x40: Union[float, str]
    x41: Union[float, str]
    x42: Union[float, str]
    x43: Union[float, str]
    x44: Union[float, str]
    x45: Union[float, str]
    x46: Union[float, str]
    x47: Union[float, str]
    x48: Union[float, str]
    x49: Union[float, str]
    x50: Union[float, str]
    x51: Union[float, str]
    x52: Union[float, str]
    x53: Union[float, str]
    x54: Union[float, str]
    x55: Union[float, str]
    x56: Union[float, str]
    x57: Union[float, str]
    x58: Union[float, str]
    x59: Union[float, str]
    x60: Union[float, str]
    x61: Union[float, str]
    x62: Union[float, str]
    x63: Union[float, str]
    x64: Union[float, str]
    x65: Union[float, str]
    x66: Union[float, str]
    x67: Union[float, str]
    x68: Union[float, str]
    x69: Union[float, str]
    x70: Union[float, str]
    x71: Union[float, str]
    x72: Union[float, str]
    x73: Union[float, str]
    x74: Union[float, str]
    x75: Union[float, str]
    x76: Union[float, str]
    x77: Union[float, str]
    x78: Union[float, str]
    x79: Union[float, str]
    x80: Union[float, str]
    x81: str
    x82: str
    x83: Union[float, str]
    x84: Union[float, str]
    x85: Union[float, str]
    x86: Union[float, str]
    x87: Union[float, str]
    x88: Union[float, str]
    x89: Union[float, str]
    x90: Union[float, str]
    x91: Union[float, str]
    x92: Union[float, str]
    x93: Union[float, str]
    x94: Union[float, str]
    x95: Union[float, str]
    x96: Union[float, str]
    x97: Union[float, str]
    x98: Union[float, str]
    x99: Union[float, str]
